### PR TITLE
Adds `ember-key-manager` as an alternative

### PR DESCRIPTION
**Pull request by patrickberkeley**

### CODE REVIEW

**Comment by lukemelia** [comment]
I have personal experience with ember-keyboard, so I feel comfortable recommending it. I don't yet have that for ember-key-manager, so I don't think I can merge this in good faith. Congrats on the addon, though @patrickberkeley!

**Comment by lukemelia** [comment]
Out of curiosity, @patrickberkeley, what was missing for you about the alternatives that led you to develop your own keyboard shortcuts addon?

**Comment by patrickberkeley** [comment]
@lukemelia makes sense on not wanting to recommend something you haven't used. Thanks for considering.

Regarding why we decided to build YAKMA (yet another key manager addon): https://medium.com/icarus-wings/building-a-keyboard-manager-service-in-ember-js-4012861a5d6f#.98jy8uyxf

**Comment by lukemelia** [comment]
@patrickberkeley terrific writeup! I'll make a point to try it out soon.

**Pull request closed without merging**
